name: Doc build

on:
  push:
    branches:
      - main

jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.x
    - name: Deploy odoc to GitHub Pages
      uses: ocaml/setup-ocaml/deploy-doc@v2
